development:
  host: 127.0.0.1
  database: atk14book_devel
  username: atk14book_devel
  password: ypGLLy

test:
  host: 127.0.0.1
  database: atk14book_test
  username: atk14book_test
  password: ypGLLy

production:
  host: 127.0.0.1
  database: atk14production
  username: atk14production
  password: ypGLLy
